---
abstract: 'A lightweight medicine for using database'
author:
  - 'ytnobody <ytnobody@gmail.com>'
build_requires:
  JSON: 0
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.6.5, CPAN::Meta::Converter version 2.132510'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Otogiri
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  Otogiri:
    file: lib/Otogiri.pm
    version: 0.05
requires:
  Class::Accessor::Lite: 0
  DBIx::Sunny: 0
  SQL::Maker: 0
  perl: 5.008005
resources:
  bugtracker: https://github.com/ytnobody/Otogiri/issues
  homepage: https://github.com/ytnobody/Otogiri
  repository: git://github.com/ytnobody/Otogiri.git
version: 0.05
x_contributors:
  - 'papix <mail@papix.net>'
  - 'Takuya Tsuchida <tsucchi@cpan.org>'
