---
abstract: 'A lightweight medicine for using database'
author:
  - 'ytnobody <ytnobody@gmail.com>'
build_requires:
  DBD::SQLite: '0'
  JSON: '0'
  Test::More: '0.98'
  Test::Time: '0'
configure_requires:
  Module::Build: '0.38'
dynamic_config: 0
generated_by: 'Minilla/v2.1.1, CPAN::Meta::Converter version 2.141520'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Otogiri
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  DBIx::Otogiri:
    file: lib/DBIx/Otogiri.pm
  DBIx::Otogiri::Iterator:
    file: lib/DBIx/Otogiri/Iterator.pm
  Otogiri:
    file: lib/Otogiri.pm
    version: '0.13'
requires:
  Class::Accessor::Lite: '0'
  DBIx::Sunny: '0'
  SQL::Maker: '1.16'
  SQL::QueryMaker: '0.02'
  perl: '5.008005'
resources:
  bugtracker: https://github.com/ytnobody/Otogiri/issues
  homepage: https://github.com/ytnobody/Otogiri
  repository: git://github.com/ytnobody/Otogiri.git
version: '0.13'
x_contributors:
  - 'papix <mail@papix.net>'
  - 'Takuya Tsuchida <tsucchi@cpan.org>'
  - 'ytnobody <ytnobody@ytnobody.net>'
